MODULE func_psi
USE use_func
IMPLICIT NONE
!INTEGER,PARAMETER::SGL=SELECTED_REAL_KIND(p=6)
!INTEGER,PARAMETER::DBL=SELECTED_REAL_KIND(p=13)
!REAL(KIND=DBL),PARAMETER::pi=3.1415926535897932385d0
!REAL(KIND=DBL),PARAMETER::EulerGamma=0.57721566490153286061d0
INTERFACE unit_step
   MODULE PROCEDURE unit_step_d
   MODULE PROCEDURE unit_step_s
   MODULE PROCEDURE unit_step_i
END INTERFACE unit_step
INTERFACE Arg
   MODULE PROCEDURE ArgI
   MODULE PROCEDURE ArgR
   MODULE PROCEDURE ArgC
END INTERFACE Arg
INTERFACE Log2
   MODULE PROCEDURE LogR
   MODULE PROCEDURE LogI
   MODULE PROCEDURE LogC
END INTERFACE Log2
INTERFACE CSQRT2
   MODULE PROCEDURE CSQRTC
   MODULE PROCEDURE CSQRTR
   MODULE PROCEDURE CSQRTI
END INTERFACE CSQRT2
INTERFACE li2
   MODULE PROCEDURE li2I
   MODULE procedure li2R
   MODULE procedure li2C
END INTERFACE li2
INTERFACE li2_QP
   MODULE PROCEDURE li2I_QP
   MODULE procedure li2R_QP
   MODULE procedure li2C_QP
END INTERFACE li2_QP
CONTAINS
FUNCTION SQRT3P(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::SQRT3P
  COMPLEX(KIND=DBL),INTENT(IN)::a
  COMPLEX(KIND=DBL)::b
  b=dcmplx(dreal(a),1D-20)
  SQRT3P=sqrt(b)
END FUNCTION SQRT3P

FUNCTION RSQRTP(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RSQRTP
  REAL(KIND=DBL),INTENT(IN)::a
  IF(a.GE.0d0)THEN
     RSQRTP=dcmplx(DSQRT(a),0d0)
  ELSE
     RSQRTP=dcmplx(0d0,DSQRT(-a))
  ENDIF
  RETURN
END FUNCTION RSQRTP

FUNCTION RSQRTM(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RSQRTM
  REAL(KIND=DBL),INTENT(IN)::a
  IF(a.GE.0d0)THEN
     RSQRTM=dcmplx(DSQRT(a),0d0)
  ELSE
     RSQRTM=dcmplx(0d0,-DSQRT(-a))
  ENDIF
  RETURN
END FUNCTION RSQRTM

FUNCTION RLOGP(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RLOGP
  REAL(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),PARAMETER::pipi=3.14159265358979323846264338328d0
  IF(a.GE.0d0)THEN
     RLOGP=dcmplx(DLOG(a),0d0)
  ELSE
     RLOGP=dcmplx(DLOG(-a),pipi)
  ENDIF
  RETURN
END FUNCTION RLOGP

FUNCTION RLOGM(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RLOGM
  REAL(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),PARAMETER::pipi=3.14159265358979323846264338328d0
  IF(a.GE.0d0)THEN
     RLOGM=dcmplx(DLOG(a),0d0)
  ELSE
     RLOGM=dcmplx(DLOG(-a),-pipi)
  ENDIF
  RETURN
END FUNCTION RLOGM

FUNCTION LOGP2(a,r)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::LOGP2
  COMPLEX(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),INTENT(IN)::r
  IF(r.GE.0d0)THEN
     LOGP2=RLOGP(dreal(a))
  ELSE
     LOGP2=LOG(a)
  ENDIF
  RETURN
END FUNCTION LOGP2

FUNCTION LOGM2(a,r)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::LOGM2
  COMPLEX(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),INTENT(IN)::r
  IF(r.GE.0d0)THEN
     LOGM2=RLOGM(dreal(a))
  ELSE
     LOGM2=LOG(a)
  ENDIF
  RETURN
END FUNCTION LOGM2

FUNCTION RLi2P(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RLi2P
  REAL(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL)::b
  REAL(KIND=DBL),PARAMETER::zeta2=1.64493406684822643647241516665d0
  IF(a.LE.1d0)THEN
     RLi2P=li2R(a)
  ELSE
     b=1d0/a
     RLi2P=-zeta2-li2R(b)-0.5d0*RLOGP(-b)**2
  ENDIF
  RETURN
END FUNCTION RLi2P

FUNCTION RLi2M(a)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::RLi2M
  REAL(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL)::b
  REAL(KIND=DBL),PARAMETER::zeta2=1.64493406684822643647241516665d0
  IF(a.LE.1d0)THEN
     RLi2M=li2R(a)
  ELSE
     b=1d0/a
     RLi2M=-zeta2-li2R(b)-0.5d0*RLOGM(-b)**2
  ENDIF
  RETURN
END FUNCTION RLi2M

FUNCTION Li2P(a,r)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::Li2P
  COMPLEX(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),INTENT(IN)::r
  IF(r.GE.0d0)THEN
     Li2P=RLI2P(dreal(a))
  ELSE
     Li2P=li2C(a)
  ENDIF
  RETURN
END FUNCTION Li2P

FUNCTION Li2M(a,r)
  IMPLICIT NONE
  COMPLEX(KIND=DBL)::Li2M
  COMPLEX(KIND=DBL),INTENT(IN)::a
  REAL(KIND=DBL),INTENT(IN)::r
  IF(r.GE.0d0)THEN
     Li2M=RLI2M(dreal(a))
  ELSE
     Li2M=li2C(a)
  ENDIF
  RETURN
END FUNCTION Li2M

FUNCTION SQRT3P_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::SQRT3P_QP
  COMPLEX(KIND(1E0_16)),INTENT(IN)::a
  COMPLEX(KIND(1E0_16))::b
  b=cmplx(real(a,kind=16),1E-20_16,kind=16)
  SQRT3P_QP=sqrt(b)
END FUNCTION SQRT3P_QP

FUNCTION RSQRTP_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RSQRTP_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  IF(a.GE.0E0_16)THEN
     RSQRTP_QP=cmplx(SQRT(a),0E0_16,kind=16)
  ELSE
     RSQRTP_QP=cmplx(0E0_16,SQRT(-a),kind=16)
  ENDIF
  RETURN
END FUNCTION RSQRTP_QP

FUNCTION RSQRTM_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RSQRTM_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  IF(a.GE.0E0_16)THEN
     RSQRTM_QP=cmplx(SQRT(a),0E0_16,kind=16)
  ELSE
     RSQRTM_QP=cmplx(0E0_16,-SQRT(-a),kind=16)
  ENDIF
  RETURN
END FUNCTION RSQRTM_QP

FUNCTION RLOGP_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RLOGP_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),PARAMETER::pipi=3.1415926535897932384626433832795028841971693993751E0_16
  IF(a.GE.0E0_16)THEN
     RLOGP_QP=cmplx(LOG(a),0E0_16,kind=16)
  ELSE
     RLOGP_QP=cmplx(LOG(-a),pipi,kind=16)
  ENDIF
  RETURN
END FUNCTION RLOGP_QP

FUNCTION RLOGM_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RLOGM_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),PARAMETER::pipi=3.1415926535897932384626433832795028841971693993751E0_16
  IF(a.GE.0E0_16)THEN
     RLOGM_QP=cmplx(LOG(a),0E0_16,kind=16)
  ELSE
     RLOGM_QP=cmplx(LOG(-a),-pipi,kind=16)
  ENDIF
  RETURN
END FUNCTION RLOGM_QP

FUNCTION LOGP2_QP(a,r)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::LOGP2_QP
  COMPLEX(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),INTENT(IN)::r
  IF(r.GE.0E0_16)THEN
     LOGP2_QP=RLOGP_QP(real(a,kind=16))
  ELSE
     LOGP2_QP=LOG(a)
  ENDIF
  RETURN
END FUNCTION LOGP2_QP

FUNCTION LOGM2_QP(a,r)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::LOGM2_QP
  COMPLEX(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),INTENT(IN)::r
  IF(r.GE.0E0_16)THEN
     LOGM2_QP=RLOGM_QP(real(a,kind=16))
  ELSE
     LOGM2_QP=LOG(a)
  ENDIF
  RETURN
END FUNCTION LOGM2_QP

FUNCTION RLi2P_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RLi2P_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16))::b
  REAL(KIND(1E0_16)),PARAMETER::zeta2=1.6449340668482264364724151666460251892189499012068E0_16
  IF(a.LE.1E0_16)THEN
     RLi2P_QP=li2R_QP(a)
  ELSE
     b=1E0_16/a
     RLi2P_QP=-zeta2-li2R_QP(b)-0.5E0_16*RLOGP_QP(-b)**2
  ENDIF
  RETURN
END FUNCTION RLi2P_QP

FUNCTION RLi2M_QP(a)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::RLi2M_QP
  REAL(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16))::b
  REAL(KIND(1E0_16)),PARAMETER::zeta2=1.6449340668482264364724151666460251892189499012068E0_16
  IF(a.LE.1E0_16)THEN
     RLi2M_QP=li2R_QP(a)
  ELSE
     b=1E0_16/a
     RLi2M_QP=-zeta2-li2R_QP(b)-0.5E0_16*RLOGM_QP(-b)**2
  ENDIF
  RETURN
END FUNCTION RLi2M_QP

FUNCTION Li2P_QP(a,r)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::Li2P_QP
  COMPLEX(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),INTENT(IN)::r
  IF(r.GE.0E0_16)THEN
     Li2P_QP=RLI2P_QP(real(a,kind=16))
  ELSE
     Li2P_QP=li2C_QP(a)
  ENDIF
  RETURN
END FUNCTION Li2P_QP

FUNCTION Li2M_QP(a,r)
  IMPLICIT NONE
  COMPLEX(KIND(1E0_16))::Li2M_QP
  COMPLEX(KIND(1E0_16)),INTENT(IN)::a
  REAL(KIND(1E0_16)),INTENT(IN)::r
  IF(r.GE.0E0_16)THEN
     Li2M_QP=RLI2M_QP(real(a,kind=16))
  ELSE
     Li2M_QP=li2C_QP(a)
  ENDIF
  RETURN
END FUNCTION Li2M_QP

FUNCTION lamda_func(a,b,c)
REAL(KIND=DBL)::lamda_func
REAL(KIND=DBL),INTENT(IN)::a,b,c
lamda_func=a**2+b**2+c**2-2*a*b-2*a*c-2*b*c
END FUNCTION lamda_func

FUNCTION unit_step_d(x)
REAL(KIND=DBL)::unit_step_d
REAL(KIND=DBL)::x
IF(x.LT.0d0) THEN
   unit_step_d=0d0
ELSE
   unit_step_d=1d0
END IF
END FUNCTION unit_step_d

FUNCTION unit_step_s(x)
REAL(KIND=DBL)::unit_step_s
REAL(KIND=SGL)::x
IF(x.LT.0.0) THEN
   unit_step_s=0d0
ELSE
   unit_step_s=1d0
END IF
END FUNCTION unit_step_s

FUNCTION unit_step_i(x)
REAL(KIND=DBL)::unit_step_i
INTEGER::x
IF(x.LT.0) THEN
   unit_step_i=0d0
ELSE
   unit_step_i=1d0
END IF
END FUNCTION unit_step_i

FUNCTION ACosh_p(x)
REAL(KIND=DBL),INTENT(IN)::x
REAL(KIND=DBL)::ACosh_p
IF(DABS(x).LT.1d0) THEN
  WRITE(*,*)"Error in ACosh_p!"
  ACosh_p=0
ELSE
  ACosh_p=DLOG(x+DSQRT(x**2-1d0))
END IF
END FUNCTION ACosh_p
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Li2 function
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION li2R(x)
  COMPLEX(KIND=DBL)::li2R
  REAL(KIND=DBL),INTENT(IN)::x
  REAL(KIND=DBL)::y
  y=1d0-x
  IF(y.GT.0d0) THEN
     !   IF(y.GT.1d0)WRITE(*,*)"ATTENTION!"
     li2R=func_li2a(y,0)
  ELSEIF(y.LT.0d0)THEN
     li2R=func_li2a(-y,1)
  ELSE
     li2R=DCMPLX(0d0)
  END IF
  RETURN
END FUNCTION li2R

FUNCTION li2I(x)
  COMPLEX(KIND=DBL)::li2I
  INTEGER,INTENT(IN)::x
  REAL(KIND(1d0))::xx
  REAL(KIND=DBL)::y
  xx=x
  y=1d0-xx
  IF(y.GT.0d0) THEN
     li2I=func_li2a(y,0)
  ELSEIF(y.LT.0d0)THEN
     li2I=func_li2a(-y,1)
  ELSE
     li2I=DCMPLX(0d0)
  END IF
  RETURN
END FUNCTION li2I

FUNCTION li2C(x)
  COMPLEX(KIND=DBL)::li2C
  COMPLEX(KIND=DBL),INTENT(IN)::x
  COMPLEX(KIND=DBL)::y,newy
  REAL(KIND=DBL)::yr,yi
  INTEGER::iphi
  y=DCMPLX(1d0)-x
  yr=DBLE(y)
  yi=DIMAG(y)
  IF(yr.EQ.0d0.AND.yi.EQ.0d0)THEN
     li2C=DCMPLX(0d0)
     RETURN
  ENDIF
  IF(yr.GE.0d0.AND.yi.GE.0d0)THEN
     iphi=0
     newy=y
  ELSEIF(yr.GE.0d0.AND.yi.LT.0d0)THEN
     iphi=0
     newy=y
  ELSEIF(yr.LT.0d0.AND.yi.GE.0d0)THEN
     iphi=1
     newy=DCMPLX(-yr,-yi)
  ELSEIF(yr.LT.0d0.AND.yi.LT.0d0)THEN
     iphi=-1
     newy=DCMPLX(-yr,-yi)
  END IF
  li2C=func_li2c(newy,iphi)
  RETURN
END FUNCTION li2C

FUNCTION PolyLog(n,x)
  COMPLEX(KIND=DBL)::PolyLog
  REAL(KIND=DBL),INTENT(IN)::x
  INTEGER,INTENT(IN)::n
  IF(n.NE.2)THEN
     WRITE(*,*)"ERROR:Don't know n = ",n
     STOP
  ENDIF
  PolyLog=li2R(x)
  RETURN
END FUNCTION PolyLog

FUNCTION li2R_QP(x)
  COMPLEX(KIND(1E0_16))::li2R_QP
  REAL(KIND(1E0_16)),INTENT(IN)::x
  REAL(KIND(1E0_16))::y
  y=1E0_16-x
  IF(y.GT.0E0_16) THEN
     li2R_QP=mp_func_li2a(y,0)
  ELSEIF(y.LT.0d0)THEN
     li2R_QP=mp_func_li2a(-y,1)
  ELSE
     li2R_QP=CMPLX(0E0_16,0E0_16,kind=16)
  END IF
  RETURN
END FUNCTION li2R_QP

FUNCTION li2I_QP(x)
  COMPLEX(KIND(1E0_16))::li2I_QP
  INTEGER,INTENT(IN)::x
  REAL(KIND(1E0_16))::xx
  REAL(KIND(1E0_16))::y
  xx=x
  y=1E0_16-xx
  IF(y.GT.0E0_16) THEN
     li2I_QP=mp_func_li2a(y,0)
  ELSEIF(y.LT.0E0_16)THEN
     li2I_QP=mp_func_li2a(-y,1)
  ELSE
     li2I_QP=CMPLX(0E0_16,0E0_16,kind=16)
  END IF
  RETURN
END FUNCTION li2I_QP

FUNCTION li2C_QP(x)
  COMPLEX(KIND=QDL)::li2C_QP
  COMPLEX(KIND=QDL),INTENT(IN)::x
  COMPLEX(KIND=QDL)::y,newy
  REAL(KIND=QDL)::yr,yi
  INTEGER::iphi
  y=CMPLX(1E0_16,0E0_16,kind=16)-x
  yr=REAL(y,kind=16)
  yi=IMAGPART(y)
  IF(yr.EQ.0E0_16.AND.yi.EQ.0E0_16)THEN
     li2C_QP=CMPLX(0E0_16,0E0_16,kind=16)
     RETURN
  ENDIF
  IF(yr.GE.0E0_16.AND.yi.GE.0E0_16)THEN
     iphi=0
     newy=y
  ELSEIF(yr.GE.0E0_16.AND.yi.LT.0E0_16)THEN
     iphi=0
     newy=y
  ELSEIF(yr.LT.0E0_16.AND.yi.GE.0E0_16)THEN
     iphi=1
     newy=CMPLX(-yr,-yi,kind=16)
  ELSEIF(yr.LT.0E0_16.AND.yi.LT.0E0_16)THEN
     iphi=-1
     newy=CMPLX(-yr,-yi,kind=16)
  END IF
  li2C_QP=mp_func_li2c(newy,iphi)
  RETURN
END FUNCTION li2C_QP

FUNCTION PolyLog_QP(n,x)
  COMPLEX(KIND(1E0_16))::PolyLog_QP
  REAL(KIND(1E0_16)),INTENT(IN)::x
  INTEGER,INTENT(IN)::n
  IF(n.NE.2)THEN
     WRITE(*,*)"ERROR:Don't know n = ",n
     STOP
  ENDIF
  PolyLog_QP=li2R_QP(x)
  RETURN
END FUNCTION PolyLog_QP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! DLOG2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION DLOG2(x)
REAL(KIND=DBL)::DLOG2
REAL(KIND=DBL),INTENT(IN)::x
IF(x.LT.0d0)THEN
   DLOG2=DLOG(-x)
ELSE
   DLOG2=DLOG(x)
ENDIF
END FUNCTION DLOG2

FUNCTION LogI(x)
  COMPLEX(KIND(1d0))::LogI
  INTEGER,INTENT(IN)::x
  REAL(KIND(1d0))::xx
  COMPLEX(KIND(1d0))::xxx
  IF(x.GT.0)THEN
     xx=x
     LogI=DLOG(xx)
  ELSE
     xxx=DCMPLX(DBLE(x),0d0)
     LogI=CDLOG(xxx)
  ENDIF
  RETURN
END FUNCTION LogI

FUNCTION LogR(x)
  COMPLEX(KIND(1d0))::LogR
  REAL(KIND(1d0)),INTENT(IN)::x
  COMPLEX(KIND(1d0))::xx
  IF(x.GT.0d0)THEN
     LogR=DLOG(x)
  ELSE
     xx=DCMPLX(x,0d0)
     LogR=CDLOG(xx)
  ENDIF
  RETURN
END FUNCTION LogR

FUNCTION LogC(x)
  COMPLEX(KIND(1d0))::LogC
  COMPLEX(KIND(1d0)),INTENT(IN)::x
  LogC=CDLOG(x)
  RETURN
END FUNCTION LogC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Arg
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION ArgR(x)
  IMPLICIT NONE
  REAL(KIND=DBL),INTENT(IN)::x
  REAL(KIND=DBL)::ArgR
  REAL(KIND=DBL),PARAMETER::pi=3.1415926535897932385d0
  IF(x.GE.0d0)THEN
     ArgR=0d0
  ELSE
     ArgR=pi
  ENDIF
  RETURN
END FUNCTION ArgR

FUNCTION ArgI(x)
  IMPLICIT NONE
  INTEGER,INTENT(IN)::x
  REAL(KIND=DBL)::ArgI
  REAL(KIND=DBL),PARAMETER::pi=3.1415926535897932385d0
  IF(x.GE.0)THEN
     ArgI=0d0
  ELSE
     ArgI=pi
  ENDIF
  RETURN
END FUNCTION ArgI

FUNCTION ArgC(x)
  IMPLICIT NONE
  COMPLEX(KIND=DBL),INTENT(IN)::x
  REAL(KIND=DBL)::ArgC
  REAL(KIND=DBL)::xr,xi
  REAL(KIND=DBL)::add,time
  REAL(KIND=DBL),PARAMETER::pi=3.1415926535897932385d0
  xr=DBLE(x)
  xi=DIMAG(x)
  IF(xr.EQ.0d0)THEN
     IF(xi.GT.0d0)THEN
        ArgC=pi/2d0
        RETURN
     ENDIF
     IF(xi.LT.0d0)THEN
        ArgC=-pi/2d0
        RETURN
     ENDIF
     IF(xi.EQ.0d0)THEN
        ArgC=0d0
        RETURN
     ENDIF
  ENDIF
  IF(xr.GE.0d0.AND.xi.GE.0d0)THEN
     add=0d0
     time=1d0
  ELSEIF(xr.GE.0d0.AND.xi.LT.0d0)THEN
     add=0d0
     time=-1d0
  ELSEIF(xr.LT.0d0.AND.xi.GE.0d0)THEN
     add=pi
     time=-1d0
  ELSEIF(xr.LT.0d0.AND.xi.LE.0d0)THEN
     add=-pi
     time=1d0
  ENDIF
  ArgC=time*atan(abs(xi/xr))+add
  RETURN
END FUNCTION ArgC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! CSQRT2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION CSQRTI(x)
  IMPLICIT NONE
  COMPLEX(KIND(1d0))::CSQRTI
  INTEGER,INTENT(IN)::x
  REAL(KIND(1d0))::xx
  COMPLEX(KIND(1d0))::xxx
  IF(x.GE.0)THEN
     xx=x
     CSQRTI=DCMPLX(DSQRT(xx))
  ELSE
     xxx=x
     CSQRTI=CDSQRT(xxx)
  ENDIF
  RETURN
END FUNCTION CSQRTI

FUNCTION CSQRTR(x)
  IMPLICIT NONE
  COMPLEX(KIND(1d0))::CSQRTR
  REAL(KIND(1d0)),INTENT(IN)::x
  COMPLEX(KIND(1d0))::xx
  IF(x.GE.0d0)THEN
     CSQRTR=DCMPLX(DSQRT(x))
  ELSE
     xx=x
     CSQRTR=CDSQRT(xx)
  ENDIF
  RETURN
END FUNCTION CSQRTR

FUNCTION CSQRTC(x)
  IMPLICIT NONE
  COMPLEX(KIND(1d0))::CSQRTC
  COMPLEX(KIND(1d0)),INTENT(IN)::x
  CSQRTC=CDSQRT(x)
  RETURN
END FUNCTION CSQRTC
END MODULE func_psi
